<?php $profile = $this->profile; ?>
<?php $this->headTitle()->prepend($profile->getName()); ?>
<?php $fulladdress = $profile->getAddress() ?>

<div class="fb-profile">
    <div class="fb-profile-container">
        <div class="profile-social">
            <?php if($profile->getGoogleplus()): ?>
                <a target="_blank" href="https://plus.google.com/<?php echo $profile->getGoogleplus() ?>"><i id="social-gp" class="fa fa-google-plus-square fa-3x  social-magnifier"></i></a>
            <?php endif; ?>

            <?php if($profile->getFacebook()): ?>
                <a target="_blank" href="<?php echo $profile->getFacebook() ?>"><i id="social-fb" class="fa fa-facebook-square fa-3x  social-magnifier"></i></a>
            <?php endif; ?>

            <?php if($profile->getInstagram()): ?>
                <a target="_blank" href="https://www.instagram.com/<?php echo $profile->getInstagram() ?>"><i id="social-em" class="fa fa-instagram fa-3x  social-magnifier"></i></a>
            <?php endif; ?>

            <?php if($profile->getTwitter()): ?>
                <a target="_blank" href="https://www.twitter.com/<?php echo $profile->getTwitter() ?>"><i id="social-tw" class="fa fa-twitter-square fa-3x  social-magnifier"></i></a>
            <?php endif; ?>

            <?php if($profile->getUrl()): ?>
                <a target="_blank" href="<?php echo $profile->getUrl()?>"><i class="fa fa-globe fa-3x  social-magnifier"></i></a>
            <?php endif; ?>
        </div>

        <?php if($profile->getFile()): ?>
            <?php if (exif_imagetype(__DIR__ . "/../../../../" . $profile->getFile())): ?>
                <img align="left" class="fb-image-lg img-responsive" src="<?php echo $profile->getFile() ?>" alt="<?php echo $profile->getName() ?>"/>
                <?php else: ?>
                <img align="left" class="fb-image-lg img-responsive" src="/img/generic.jpg" alt="<?php echo $profile->getName() ?>"/>
            <?php endif; ?><?php else: ?>
            <img align="left" class="fb-image-lg img-responsive" src="/img/generic.jpg" alt="<?php echo $profile->getName() ?>"/>
        <?php endif; ?>

    </div>

    <span class="hidden-xs">
        <?php if (exif_imagetype(__DIR__ . "/../../../../" . $profile->getFile())): ?>
            <img align="left" class="fb-image-profile thumbnail" src="<?php echo $profile->getFile() ?>" alt="<?php echo $profile->getName() ?>"/>
            <?php else: ?>
            <img align="left" class="fb-image-profile thumbnail" src="/img/generic.jpg" alt="<?php echo $profile->getName() ?>"/>
        <?php endif; ?>
    </span>

    <div class="fb-profile-text">
        <h1><?php echo $profile->getName() ?>
            <small> <?php echo $profile->getSlogan(); ?></small>
        </h1>
    </div>
</div>



<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="col-md-8 profile-description">
                <?php if($profile->getFile()): ?>
                    <?php if (!exif_imagetype(__DIR__ . "/../../../../" . $profile->getFile())): ?>
                        <a class="btn btn-success" href="<?php echo $profile->getFile() ?>"><?php echo $this->translate('Download')?></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php echo $profile->getBiography() ? $profile->getBiography() : $this->translate('No description has been found!') ?>
            </div>
            <div class="col-md-4">
                <?php if($profile->getLatitude() && $profile->getLongitude()): ?>
                    <?php echo $this->createMap(array('latitude' => $profile->getLatitude(), 'longitude' => $profile->getLongitude()), 16)?>
                <?php endif;?>

                <address>
                  <strong><?php echo $profile->getName(); ?></strong> <small><?php echo $profile->category ?></small><br>
                    <a href="https://www.google.com/maps/place/<?php echo urlencode($fulladdress)?>" target="_blank"><i class="fa fa-location-arrow"></i> <?php echo $fulladdress; ?></a><br/>

                    <?php if($profile->getTelephone()): ?>
                        <abbr title="<?php echo $this->translate('Phone')?>">P:</abbr> <a href="callto://<?php echo $profile->getTelephone()?>"><?php echo $profile->getTelephone()?></a>
                    <?php endif; ?>
                </address>

            </div>
        </div>
    </div>

    <h3><i class="fa fa-calendar"></i> <?php echo $this->translate('Our Events')?> <small><?php echo $this->translate('Discover our events')?></small></h3>
    <p><?php echo $this->translate('Click on the following events to know more details.')?></p>
    <?php echo $this->events($profile->getUserid())?>


    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <span title="<?php echo $this->translate('Signed up')?>" class="label label-success"><i class="fa fa-refresh"></i> <?php echo $this->datetime($profile->getCreatedat(), 'dd/MM/Y') ?></span>
                <span title="<?php echo $this->translate('Update time')?>" class="label label-default"><i class="fa fa-refresh"></i> <?php echo $this->datetime($profile->getUpdatedat(), 'dd/MM/Y') ?></span>
            </div>
            <div class="col-lg-4 text-right">
                <?php if($profile->getPaypal()): ?>
                    <img width="100" class="img-responsive img-thumbnail" src="/img/paypal.gif" />
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

